//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotExpander {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LEStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LEStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LotExpander.LEStrings", typeof(LEStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wall conversion was aborted!.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Advanced....
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Browse....
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No walls were changed.
        ///	
        ///No walls matched the criteria specified..
        /// </summary>
        internal static string ChangedNoWalls {
            get {
                return ResourceManager.GetString("ChangedNoWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 wall has been changed..
        /// </summary>
        internal static string ChangedWall {
            get {
                return ResourceManager.GetString("ChangedWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} walls have been changed..
        /// </summary>
        internal static string ChangedWalls {
            get {
                return ResourceManager.GetString("ChangedWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wall conversion was aborted! An error occurred during modification of your lot. The current version of ConvertiWall is unable to continue.
        ///
        ///Please report this error in the download thread and attach a copy of your lot to the posting.
        ///	.
        /// </summary>
        internal static string ExplainAbort {
            get {
                return ResourceManager.GetString("ExplainAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///You have chosen not to continue with the wall conversion.
        ///	.
        /// </summary>
        internal static string ExplainUserAbort {
            get {
                return ResourceManager.GetString("ExplainUserAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Lot:.
        /// </summary>
        internal static string LotTitle {
            get {
                return ResourceManager.GetString("LotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you continue, ConvertiWall may corrupt your lot.
        ///Do not continue unless you have a current backup.
        ///
        ///Do you really want to continue?
        ///	.
        /// </summary>
        internal static string MessageCorruptLot {
            get {
                return ResourceManager.GetString("MessageCorruptLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported version: {0}.
        ///	
        ///ConvertiWall only supports Expansion and Stuff Packs
        ///up to and including {1}.
        ///
        ///Do you want to continue?
        ///	.
        /// </summary>
        internal static string MessageWrongVer {
            get {
                return ResourceManager.GetString("MessageWrongVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Neighbourhood:.
        /// </summary>
        internal static string NBTitle {
            get {
                return ResourceManager.GetString("NBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///There are no lots available in the currently selected neighborhood.
        ///
        ///Click Back to select another neighborhood.
        ///.
        /// </summary>
        internal static string NoLot {
            get {
                return ResourceManager.GetString("NoLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Lots Available.
        /// </summary>
        internal static string NoLotTitle {
            get {
                return ResourceManager.GetString("NoLotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Neighborhoods Available.
        /// </summary>
        internal static string NoNBTitle {
            get {
                return ResourceManager.GetString("NoNBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///There are no neighborhoods available in the standard Sims 2 location.
        ///
        ///Click Browse... to select a neighborhood.
        ///.
        /// </summary>
        internal static string NoNeighborhood {
            get {
                return ResourceManager.GetString("NoNeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the old and new Wall IDs,
        ///and the range of walls to convert.
        ///	.
        /// </summary>
        internal static string SpecificationExpl {
            get {
                return ResourceManager.GetString("SpecificationExpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING!  Unsupported Version..
        /// </summary>
        internal static string TitleCorruptLot {
            get {
                return ResourceManager.GetString("TitleCorruptLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING!  Unsupported Version..
        /// </summary>
        internal static string TitleWrongVer {
            get {
                return ResourceManager.GetString("TitleWrongVer", resourceCulture);
            }
        }
    }
}
